export const ActionType = {
    SET_ALL_BLOGS: "SET_ALL_BLOGS",
    SET_TOP_MAIN_BLOG: "SET_TOP_MAIN_BLOG",
    SET_TOP_SUB_BLOGS: "SET_TOP_SUB_BLOGS",
    SET_NEWS_BLOGS: "SET_NEWS_BLOGS",
    SET_BUISNESS_BLOGS: "SET_BUISNESS_BLOGS",
    SET_AFFILIATE_BLOGS: "SET_AFFILIATE_BLOGS",
    SET_SOCIOLOGY_BLOGS: "SET_SOCIOLOGY_BLOGS",
    SET_TECH_BLOGS: "SET_TECH_BLOGS",
    SET_ECONOMICS_BLOGS: "SET_ECONOMICS_BLOGS",
    SET_OTHER_BLOGS: "SET_OTHER_BLOGS",
    SET_SINGLE_BLOG: "SET_SINGLE_BLOG",
    SET_LATEST_BLOGS: "SET_LATEST_BLOGS",
}